[[language]]
name = "astro"
formatter = { command = "bun", args = ["prettier", "--parser", "astro"] }
[[language]]
name = "typescript"
formatter = { command = "bun", args = ["prettier", "--parser", "typescript"] }
