name: Check
on: pull_request
jobs:
  build-type-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-bun@v2
        with:
          bun-version: "1.2.4"
      - run: bun install --frozen-lockfile
      - run: bun check
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-astro-build
          path: |
            .astro
            dist
            node_modules/.astro/assets
          restore-keys: ${{ runner.os }}-astro-build
      - run: bun run build
