name: Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5
      - run: bun install --frozen-lockfile
      - run: bun check
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.5
      - run: bun install --frozen-lockfile
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-astro-build
          path: |
            .astro
            dist
            node_modules/.astro/assets
          restore-keys: ${{ runner.os }}-astro-build
      - run: bun run build
