on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          path: |
            .cache
            public
          restore-keys: ${{ runner.os }}-gatsby-build-
      - run: npm run build
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - run: npm run type-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - run: npm run lint
